# Generated by Django 5.1.5 on 2025-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Seller'), ('seeker', 'Buyer')], default='seeker', max_length=10),
        ),
    ]
